// <auto-generated />
using FirstCatering.API.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FirstCatering.API.Migrations
{
    [DbContext(typeof(EmployeeDataContext))]
    [Migration("20200218130133_updateTable")]
    partial class updateTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FirstCatering.API.Entities.EmployeeData", b =>
                {
                    b.Property<string>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(120);

                    b.Property<decimal>("Balance");

                    b.Property<string>("CardId")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("MobileNumber")
                        .IsRequired();

                    b.Property<string>("Pin")
                        .IsRequired();

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new { EmployeeId = "HarveyP123", Balance = 21.00m, CardId = "r7jTG7dqBy5wGO4L", Email = "harveypinewood@bowsf1.com", FirstName = "Harvey", LastName = "Pinewood", MobileNumber = "+447123456760", Pin = "1234" },
                        new { EmployeeId = "GeorgiaY123", Balance = 22.00m, CardId = "r7jTG7dqBy5wGO3L", Email = "georgiayale@bowsf1.com", FirstName = "Georgia", LastName = "Yale", MobileNumber = "+447123456769", Pin = "1234" },
                        new { EmployeeId = "PaulF123", Balance = -1.00m, CardId = "r7jTG7dqBy5wGO2L", Email = "paulforest@bowsf1.com", FirstName = "Paul", LastName = "Forest", MobileNumber = "+447123456789", Pin = "1234" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
